# ███████╗ ██████╗ ██╗   ██╗██████╗  ██████╗███████╗███████╗
# ██╔════╝██╔═══██╗██║   ██║██╔══██╗██╔════╝██╔════╝██╔════╝
# ███████╗██║   ██║██║   ██║██████╔╝██║     █████╗  ███████╗
# ╚════██║██║   ██║██║   ██║██╔══██╗██║     ██╔══╝  ╚════██║
# ███████║╚██████╔╝╚██████╔╝██║  ██║╚██████╗███████╗███████║
# ╚══════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝ ╚═════╝╚══════╝╚══════╝

source = ~/.config/rice/custom_binds.conf
source = ~/.config/rice/window_rules.conf
source = ~/.config/rice/general.conf